### ISSUE TITLE
HFRnet Thredds Timing out: OPeNDAP ERROR -70 

### ISSUE THREAD

**Issue by patcdaniel** [rowg/HFRnet-Thredds-support#1]
Hello, 
The HFRnet TDS has been timing out when I try to access the 2km West Coast, returning the following:

`[Errno -70] NetCDF: DAP server error: b'http://hfrnet-tds.ucsd.edu/thredds/dodsC/HFR/USWC/2km/hourly/RTV/HFRADAR_US_West_Coast_2km_Resolution_Hourly_RTV_best.ncd'`

I attempting to lazy-load the data into an Xarray dataset and slice it up into a smaller region (ie Monterey Bay or San Francisco) and then perform some calculations. In maybe 1 out of 5 tries the request goes through, but most of the time it times out.

Is there any insight into either better practices (what I'm doing is very inline with the other notebooks here) or why the HFRnet TDS seems to currently be unreliable?

Thanks,

Patrick Daniel
CeNCOOS Data Manager

**Comment by tc33133** [comment]
There's been some sluggishness on the server lately, and I'm trying to get to the bottom of it. 
I'm not sure how much data you are requesting, but the 2km grid is very dense, and if you are having issues you might want to chunk your requests into shorter time intervals (2-3 weeks). The problem is that Thredds isn't great about prescreening requests and sometimes a bad request will overwhelm the server and slow it down severely, but not kill it. Unfortunately, the best way around this is to manually reboot the server.  I just restarted the server (2/3/2020 3:10pm PT), try again and let me know what you find. In the future please email hfrnet.administrators@sio.ucsd.edu for quickest support.

**Comment by tc33133** [comment]
Hi Patrick, I found a rogue user initiating large numbers of requests and downloading a large amount of data, which was causing sluggish performance of the server. I've blocked the user and things are more stable now. Let me know if you are still having issues.

**Comment by patcdaniel** [comment]
@tc33133 Yes, it is significantly faster this morning. It worked for me yesterday after your reset the server, but was still fairly slow. Thanks for responding so quickly!
